### ISSUE TITLE
Credit to Original Author

### ISSUE THREAD

**Issue by zarethrex** [RIOzSignal/railway-dot-exe-sinicized#1]
The Railway Operation Simulator community kindly requests that you reinstate credit to the original author of this program Albert Ball. The software is available under GPLv3 under the understanding that you will keep credit to those who have put work into it's development. 

Original Source repository: https://github.com/Railway-Op-Sim/railway-dot-exe

**Comment by RIOzSignal** [comment]
Hi, Kristian Zarębski
README.md has been updated
【THIS SOFTWARE IS PROVIDED BY Albert Ball】
【THIS SOFTWARE IS SINICIZED BY RIO≒Signal调度模拟Xeon_HSU】
Should I have to add more statement, thanks for your help.
Xeon_HSU
------------------------------------------------------------------
From:Kristian Zarębski ***@***.***>
Send Time:2023年2月17日(星期五) 03:20
To:RIOzSignal/railway-dot-exe-sinicized ***@***.***>
Cc:Subscribed ***@***.***>
Subject:[RIOzSignal/railway-dot-exe-sinicized] Credit to Original Author (Issue #1)
The authors of Railway Operation Simulator kindly request that you reinstate credit to the original author of this program Albert Ball. The software is available under GPLv3 under the understanding that you will keep credit to those who have put work into it's development.

**Comment by zarethrex** [comment]
Thank you, Albert put a lot of work and many years into it not to be credited, I am sure he appreciates the recognition.

**Comment by RIOzSignal** [comment]
Hi, Kristian Zarębski
It was my oversight by default, Albert and I've known each other for 6 years, and got permission to sinicized. Thank you for your timely correction.
Xeon_HSU
------------------------------------------------------------------
From:Kristian Zarębski ***@***.***>
Send Time:2023年2月22日(星期三) 01:56
To:RIOzSignal/railway-dot-exe-sinicized ***@***.***>
Cc:RIO≒Signal调度模拟 ***@***.***>; Comment ***@***.***>
Subject:Re: [RIOzSignal/railway-dot-exe-sinicized] Credit to Original Author (Issue #1)
Thank you, Albert put a lot of work and many years into it not to be credited, I am sure he appreciates the recognition.
